### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by alihastam** [imanghafoori1/laravel-password-history#13]
Hi , I installed and used this package but it did not work for me
![2020-09-04_075545](https://user-images.githubusercontent.com/36451636/92197161-3aef2180-ee86-11ea-9646-981ffe8ab674.jpg)

I have this error repeatedly : `The password has been used before.`
![2020-09-04_075417](https://user-images.githubusercontent.com/36451636/92197244-74279180-ee86-11ea-9dea-dcfacddf5cfe.jpg)

**Comment by imanghafoori1** [comment]
@mehradsadeghi

**Comment by mehradsadeghi** [comment]
> @mehradsadeghi

@imanghafoori1 
I'll take a look at it.

**Comment by mehradsadeghi** [comment]
> @mehradsadeghi

@imanghafoori1 

I guess this is directly related to the PR (#11) I sent before which got rejected.

Please take a look at [these unit tests](https://github.com/imanghafoori1/laravel-password-history/pull/11/files#diff-d47d7b7c2ad3663f7cc8ff6f1c7fd25a) I wrote in that PR.

These unit tests do not pass with the current implementation of `PasswordHistory` Which made me change the behavior of this part:
https://github.com/imanghafoori1/laravel-password-history/blob/2afdadc291cdaea1152e6dd6b63a8075a3881d1f/src/PasswordHistory.php#L39-L51

**Comment by imanghafoori1** [comment]
@mehradsadeghi Thank you very much Mehrad. 
The PR git merged,
Try out the latest version. v0.1.4

**Comment by mehradsadeghi** [comment]
> @mehradsadeghi Thank you very much Mehrad.
> The PR git merged,
> Try out the latest version. v0.1.4

@imanghafoori1 

You're welcome.
I think the latest released version is v0.1.3

**Comment by mehradsadeghi** [comment]
@alihastam 

If the issue still exists with the latest released version, Please notify us.

**Comment by imanghafoori1** [comment]
closing on inactivity.
