### ISSUE TITLE
Releasing Latest Version

### ISSUE THREAD

**Issue by mehradsadeghi** [imanghafoori1/laravel-password-history#7]
Hello Iman,
It seems you haven't released the latest version of this package on packagist. Latest version there is v0.0.2 which has error at installation process.
![Screenshot from 2020-08-10 22-50-42](https://user-images.githubusercontent.com/31504728/89817356-44be8700-db5d-11ea-9321-7b5cbf2e73d9.png)

I started digging into the source code and found out the error is because of a bug which is fixed in  v0.1.0

Am I missing something or you have to release the latest version ?

**Comment by imanghafoori1** [comment]
will check it out

**Comment by imanghafoori1** [comment]
Try v0.1.1

**Comment by mehradsadeghi** [comment]
> Try v0.1.1

Thank you. I'll check it out later today. I guess it should be fine so I close this issue for now. 
If there were any problem, I'll reopen it.
